import pandas as pd

def create_features(df):
    """
    Function to create new features for the dataset.
    Parameters:
    df (pd.DataFrame): Input dataframe with raw data.
    
    Returns:
    pd.DataFrame: Dataframe with new features.
    """
    # Ensure 'timestamp' column is datetime
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    
    # Create rolling mean features
    df['temp_rolling_mean'] = df['temperature'].rolling(window=5).mean()
    df['pressure_rolling_mean'] = df['pressure'].rolling(window=5).mean()
    df['vibration_rolling_mean'] = df['vibration'].rolling(window=5).mean()
    
    # Create rolling std features
    df['temp_rolling_std'] = df['temperature'].rolling(window=5).std()
    df['pressure_rolling_std'] = df['pressure'].rolling(window=5).std()
    df['vibration_rolling_std'] = df['vibration'].rolling(window=5).std()
    
    # Create lag features
    df['temp_lag_1'] = df['temperature'].shift(1)
    df['pressure_lag_1'] = df['pressure'].shift(1)
    df['vibration_lag_1'] = df['vibration'].shift(1)
    
    # Drop rows with NaN values generated by rolling and lag operations
    df.dropna(inplace=True)
    
    return df

def main():
    # Load the raw data
    raw_data_path = r'C:\Users\anoushka chatterjee\Desktop\project\data\raw\equipment_data.csv'
    df = pd.read_csv(raw_data_path)
    
    # Create new features
    df_with_features = create_features(df)
    
    # Save the dataframe with new features
    processed_data_path = r'C:\Users\anoushka chatterjee\Desktop\project\data\processed\equipment_data_with_features.csv'
    df_with_features.to_csv(processed_data_path, index=False)
    print(f"Feature engineering completed and saved to {processed_data_path}")

if __name__ == "__main__":
    main()
